<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>without-it_td_a</name>
   <tag></tag>
   <elementGuidId>04696a9a-dcf4-4a52-b25f-6526b5b6f21f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id=&quot;without-it&quot;]/tbody/tr/td/a
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id=&quot;without-it&quot;]/tbody/tr/td/a
</value>
   </webElementProperties>
</WebElementEntity>
