<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>with-it_td_a_onclick</name>
   <tag></tag>
   <elementGuidId>52d63be9-d149-4c15-a2c5-653a08e153df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id=&quot;with-it&quot;]/tbody/tr/td/a[starts-with(@on-click,'javascript:selectday(')]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id=&quot;with-it&quot;]/tbody/tr/td/a[starts-with(@on-click,'javascript:selectday(')]
</value>
   </webElementProperties>
</WebElementEntity>
